var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
   "  xxxxxxxxxxx                                x             xx    xx!xx       x  ",
   "  xxxxxxxxx                         o o      x  o                x!!!x       x  ",
   "  xxxxxxx                                  xxxxxx                xx!xx       x  ",
   "  xxxxx                            xxxxx         x                xvx        x  ",
   "  xxxx          h                    x           xx   x                     xx  ",
   "  xxx           x                    x    o o                                x  ",
   "  xx           xx       o            x                  x                    x  ",
   "  x           xxx      xxx     xxxxxxx    xxxx                             o x  ",
   "  x          xxxx       o                                                    x  ",
   "  x  @     x x  x                                          x     xxxxxSSSSSSSx  ",
   "  xxxxxxxxxxxx  x    xxxxxxxxxx   xxxxx   o    xxxxxxx     xxxxxxx   xxxxxxxxx  ",
   "                x!!!!x        x   x   x  xxxx  x     x     x                    ",
   "                x!!!!x        x!!!x   x!!!!!!!!x     x!!!!!x                    ",
   "                xxxxxx        x!!!x   x!!!!!!!!x     x!!!!!x                    ",
   "                              xxxxx   xxxxxxxxxx     xxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  ["                                      x!!x                        xxxxxxx                                    x!x  ",
   "                                      x!!x                     xxxx     xxxx                                 x!x  ",
   "                                      x!!xxxxxxxxxx           xx           xx                                x!x  ",
   "                                      xx!!!!!!!!!!xx         xx             xx                               x!x  ",
   "                                       xxxxxxxxxx!!x         x                x                              x!x  ",
   "                                                xx!x         x     o   o       x                            xx!x  ",
   "                                                 x!x         x                 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!x  ",
   "                                                 xvx         x     x   x                 !!!!!!!!!!!!!!!!!!!!!xx  ",
   "                                                             xx  |   |   |  x            !xxxxxxxxxxxxxxxxxxxxx   ",
   "                                                              xx!!!!!!!!!!!xxxxxxx       v   x                    ",
   "                                                               xxxx!!!!!xxxx     x           x                    ",
   "                      xxxxxxxx                 xxxxxxx            xxxxxvxx       xx          xxx                  ",
   "                              xxxxxxxxx        x     x                   x       x x         x x                  ",
   "                                      x        x     xxxxxxxxxxxxxxxxxx xx         x         x                    ",
   "                     x                x        xo    x                   x         xxx     xxx                    ",
   "              x               x       x        xx    x                   x         x         x                    ",
   "     o        !!!!!!!!xxxxxxxxx       x        x            o  o     x   x         x         x                    ",
   "     x        !xxxxxxxx       xxx   xxx        x                     x   x         x         x                    ",
   "             !xx     xx         x   x          x     xxxxxxxxxxxxxxxxx   x   xxxxxxxxx       x                    ",
   "          x !xx       xx        x o x          x    xx               x   x   x               x                    ",
   "     @      vx         x        x h x          x     x               x   x   x              xx                    ",
   "    xxx      x         x        x   x          x     x               xx  xxxxx   xxxxxx      x                    ",
   "    x x      x         x       xx o xx         x     x               x     o     x x         x                    ",
   "!!!!x x!!!!!!x         x!!!!!!xx     xx!!!!!!!!xx    x!!!!!!!!!!     x           x x         x                    ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxx     x!!!!!!!xx!     xx!xxxxxxxxxx xx  oxo  xx                    ",
   "!!!!x x!!!!!!x         x!!!!!x    o                 xx!!!!!!xx !       x            xx     xx                     ",
   "!!!!x x!!!!!!x         x!!!!!x              =      xx!!!!!!xx  !                     xxxxxxx                      ",
   "!!!!x x!!!!!!x         x!!!!!xxSSSSSSSxxxxxxxxxxxxxx!!!!!!xx   !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx    !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                 ",
   "xxxxxxxxxxxxxxxxxxx    xxxxxxxxxx     xxxxxxx     vxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                 ",
   "xxxxxxxxxxxxx           xxxxxxx        vxxxv                xxxxxxxxxxxxxxxxxxxx                                 ",
   "xxxxxxxxxxx                xxx           x                       xxxxxxxxxxxxxxx                                 ",
   "xxxx                         x           v                           xxxxxxxxxxx                                 ",
   "xxxx o                       v                                         xxxxxxxxx                                 ",
   "xxxxxxxx                                                                xxxxxxxx                                 ",
   "xxxxxxxxxx                                                                  xxxx                                 ",
   "xxxxxxxxxxxx                                                               xxxxx                                 ",
   "xxxxxxxxxxxxxx                                                               xxx                                 ",
   "xxxxxxxxxxxxxxxx                                                              xx                                 ",
   "xxxxxxxxxxxxxxxxxxxxxx                                oo                     xxx                                 ",
   "xxxxxxxxxxxxxxxxxxxx                  o          xxxxxxxxxxxxR                xxxx                               ",
   "xxxxxxxxxxxxxxxxxxxx                o            v   xxxx                    !!!!x                               ",
   "xxxx                     xxx      o     xxxxx         xx                     !xxxx                               ",
   "xxxx                                        v        xxxx      x              xx                                 ",
   "xxxx                          xxxx               xxxxxxxxxxxx  xxxxR          vx                                 ",
   "xxxx   @                                             xxxx      xx      o       x                                 ",
   "xxxxxxxxxxxxxxx    xxxxxxx             xxxxxxxx o o o xx       xx      o       x                                 ",
   "xxxxxxxxxxxxxxx!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxx!!!!!!!xx      o       x                                 ",
   "!!!!!!!!!!!!!xx!!!!xx!!!!!!!!xxxxxxxx!!!!!!!!xxxxxxxxxxx!!!!!!!xx      o       x                                 ",
   "!!!!!!!!!!!!!xx!!!!xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx      o   x!!!x                                 ",
   "!!!!!!!!!!!!!xxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxx                                 ",
   "!!!!!!!!!!!!!xxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                                 "],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
