var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
   "  xxxxxxxxxxx                                x      x      xx    xx!xx       x  ",
   "  xxxxxxxxx                         o o      x  o                x!!!x       x  ",
   "  xxxxxxx                                  xxxxxx                xx!xx       x  ",
   "  xxxxx                            xxxxx                          xvx        x  ",
   "  xxxx          h                    x                                      xx  ",
   "  xxx           x                    x    o o                                x  ",
   "  xx           xx       o            x                                       x  ",
   "  x           xxx      xxx     xxxxxxx   xxxxx                             o x  ",
   "  x          xxxx       o                                                    x  ",
   "  x  @     x x  x                                                xxxxxSSSSSSSx  ",
   "  xxxxxxxxxxxx  x    xxxxxxxxxx   xxxxx   o    xxxxxxx     xxxxxxx   xxxxxxxxx  ",
   "                x!!!!x        x   x   x   xx   x     x     x                    ",
   "                x!!!!x        x!!!x   x!!!!!!!!x     x!!!!!x                    ",
   "                xxxxxx        x!!!x   x!!!!!!!!x     x!!!!!x                    ",
   "                              xxxxx   xxxxxxxxxx     xxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  ["                                      x!!x                        xxxxxxx                                    x!x  ",
   "                                      x!!x                     xxxx     xxxx                                 x!x  ",
   "                                      x!!xxxxxxxxxx           xx           xx                                x!x  ",
   "                                      xx!!!!!!!!!!xx         xx             xx                               x!x  ",
   "                                       xxxxxxxxxx!!x         x                x                              x!x  ",
   "                                                xx!x         x     o   o       x                            xx!x  ",
   "                                                 x!x         x                 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!x  ",
   "                                                 xvx         x     x   x                 !!!!!!!!!!!!!!!!!!!!!xx  ",
   "                                                             xx  |   |   |  xxxxx        !xxxxxxxxxxxxxxxxxxxxx   ",
   "                                                              xx!!!!!!!!!!!xx    x       v   x                    ",
   "                                                               xxxx!!!!!xxxx     x           x                    ",
   "                      xxxxxxxx                 xxxxxxx            xxxxxvxx       xx          xxx                  ",
   "                              xxxxxxxxx        x     x                   x       x x         x x                  ",
   "                                      x        x     xxxxxxxxxxxxxxxxxx xx         x         x                    ",
   "                     x                x        xo    x                   x         xxx     xxx                    ",
   "              x               x       x        xx    x                   x         x         x                    ",
   "     o        !!!!!!!!xxxxxxxxx       x        x            o  o     x   x         x         x                    ",
   "     x        !xxxxxxxx       xxx   xxx        x                     x   x         x         x                    ",
   "             !xx     xx         x   x          x     xxxxxxxxxxxxxxxxx   x   xxxxxxxxx       x                    ",
   "          x !xx       xx        x o x          x    xx               x   x   x               x                    ",
   "     @      vx         x        x   x          x     x               x   x   x              xx                    ",
   "    xxx      x         x        x   x          x     x               xx  xxxxx   xxxxxx      x                    ",
   "    x x      x         x       xx o xx         x     x               x     o     x x         x                    ",
   "!!!!x x!!!!!!x         x!!!!!!xx     xx!!!!!!!!xx    x!!!!!!!!!!     x           x x         x                    ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxx     x!!!!!!!xx!     xx!xxxxxxxxxx xx  oxo  xx                    ",
   "!!!!x x!!!!!!x         x!!!!!x    o                 xx!!!!!!xx !       x            xx     xx                     ",
   "!!!!x x!!!!!!x         x!!!!!x                     xx!!!!!!xx  !                     xxxxxxx                      ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxxxxxx!!!!!!xx   !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx    !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !                                                  "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                        o                                                                     ",
   "                                                                                                              ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                       xxx                                                                    ",
   "                                       x x                 !!!        !!!  xxx                                ",
   "                                       x x                 !x!        !x!                                     ",
   "                                     xxx xxx                x          x                                      ",
   "                                      x   x                 x   oooo   x       xxx                            ",
   "                                      x   x                 x          x      x!!!x                           ",
   "                                      x   x                 xxxxxxxxxxxx       xxx                            ",
   "                                     xx   xx      x   x      x                                                ",
   "                                      x   xxxxxxxxx   xxxxxxxx              x x                               ",
   "                                      x   x           x                    x!!!x                              ",
   "                                      x   x           x                     xxx                               ",
   "                                     xx   xx          x                                                       ",
   "                                      x   x= = = =    x            xxx                                        ",
   "                                      x   x           x           x!!!x                                       ",
   "                                      x   x    = = = =x     o      xxx       xxx                              ",
   "                                     xx   xx          x                     x!!!x                             ",
   "                              o   o   x   x           x     x                xxv        xxx                   ",
   "                                      x   x           x              x                 x!!!x                  ",
   "                             xxx xxx xxx xxx     o o  x!!!!!!!!!!!!!!x                   vx                   ",
   "                             x xxx x x xxx x          x!!!!!!!!!!!!!!x                                        ",
   "                             x             x   xxxxxxxxxxxxxxxxxxxxxxx                                        ",
   "                             xx           xx                                         xxx                      ",
   "  xxx                         x     x     x                                         x!!!x                xxx  ",
   "  x x                         x    xxx    x                                          xxx                 x x  ",
   "  x                           x    xxx    xxxxxxx                        xxxxx                             x  ",
   "  x                           x           x                              x   x                             x  ",
   "  x                           xx          x                              x x x                             x  ",
   "  x                                       x       |xxxx|    |xxxx|     xxx xxx                             x  ",
   "  x                xxx             o o    x                              x         xxx                     x  ",
   "  x               xxxxx       xx          x                             xxx       x!!!x          x         x  ",
   "  x               oxxxo       x    xxx    x                             x x        xxx          xxx        x  ",
   "  x                xxx        xxxxxxxxxxxxx  x oo x    x oo x    x oo  xx xx                    xxx        x  ",
   "  x      @          x         x           x!!x    x!!!!x    x!!!!x    xx   xx                    x         x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
